version: '2.2'
services:
  api:
    command: "uvicorn network_api.asgi:app --limit-concurrency 50 --lifespan on --host 0.0.0.0 --port 8080"
    build:
      context: backend
      dockerfile: compose/Dockerfile

    volumes:
      - ./backend/src:/var/lib/network-api/src

    env_file:
      - backend/compose/dev/app.env
    restart: always
    cpus: 1.0
    mem_limit: "67108864"

  db:
    image: mysql:5.7.32
    env_file:
      - backend/compose/dev/db.env
    volumes:
      - ./backend/compose/db/master:/etc/mysql/conf.d

    restart: always
    cpus: 1.0
    mem_limit: "268435456"

  db_slave_1:
    image: mysql:5.7.32
    env_file:
      - backend/compose/dev/db.env
    volumes:
      - ./backend/compose/db/slave_1:/etc/mysql/conf.d
    restart: always
    cpus: 1.0
    mem_limit: "268435456"

  db_slave_2:
    image: mysql:5.7.32
    env_file:
      - backend/compose/dev/db.env
    volumes:
      - ./backend/compose/db/slave_2:/etc/mysql/conf.d
    restart: always
    cpus: 1.0
    mem_limit: "268435456"

  frontend:
    restart: always
    depends_on:
      - api
    image: nginx:1.18.0-alpine
    ports:
      - 8083:80
    volumes:
      - ./frontend/src:/usr/share/nginx/html:ro
      - ./frontend/compose/default.conf:/etc/nginx/conf.d/default.conf
    cpus: 1.0
    mem_limit: "67108864"

  netdata:
    cpus: 1.0
    mem_limit: "67108864"
    image: netdata/netdata
    container_name: netdata
    hostname: example.com # set to fqdn of host
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /:/host:ro


volumes:
  netdataconfig:
  netdatalib:
  netdatacache: