version: '3'
services:
  api:
    build:
      context: backend
      dockerfile: compose/Dockerfile

    volumes:
      - ./backend/src:/var/lib/network-api/src
    ports:
      - ${DEV_API_PORT:-8082}:8080

    env_file:
      - backend/compose/dev/app.env

  db:
    image: mysql:5.7.32
    env_file:
      - backend/compose/dev/db.env

  frontend:
    image: nginx:1.18.0-alpine
    ports:
      - ${DEV_FRONTEND_PORT:-8083}:80
    volumes:
      - ./frontend/src:/usr/share/nginx/html:ro
      - ./frontend/compose/default.conf:/etc/nginx/conf.d/default.conf